add driver config files
It's useful to be able to initialize drivers in a data-driven way so you
don't have to recompile code that uses hound in order to change the
drivers being used.

Add an optional config file format for specifying driver init options,
as well as corresponding unit tests.

diff --git a/meson/schema-check b/meson/schema-check
--- a/meson/schema-check
+++ b/meson/schema-check
@@ -2,27 +2,36 @@
 
 set -uo pipefail
 
+check_schema() {
+    local schema="$1"
+    local data="$2"
+
+    if [[ ! -f $data ]]; then
+        continue
+    fi
+    if [[ $data == $schema ]]; then
+        continue
+    fi
+
+    CMD=""$MESON_SOURCE_ROOT/scripts/schema-check" \
+             -s "$schema" \
+             "$data""
+    $CMD
+    if [[ $? != 0 ]]; then
+        echo "FAILED: $CMD" >&2
+        exit 1
+    fi
+}
+
 # Check for sschema, needed for schema checking.
 python3 -c "import sschema"
 if [[ $# != 0 ]]; then
     echo 'Cannot import python module sschema. Please run "pip3 install sschema"' >&2
 fi
 
-SCHEMA_FILE="$MESON_SOURCE_ROOT/schema/meta/schema.yaml"
-for datafile in "$MESON_SOURCE_ROOT"/schema/deploy/*; do
-    if [[ ! -f $datafile ]]; then
-        continue
-    fi
-    if [[ $datafile == $SCHEMA_FILE ]]; then
-        continue
-    fi
-
-    CMD=""$MESON_SOURCE_ROOT/scripts/schema-check" \
-             -s "$SCHEMA_FILE" \
-             "$datafile""
-    $CMD
-    if [[ $? != 0 ]]; then
-        echo "FAILED: $CMD" >&2
-        exit 1
-    fi
+for datafile in "$MESON_SOURCE_ROOT"/schema/driver/deploy/*; do
+    check_schema "$MESON_SOURCE_ROOT/schema/driver/meta/schema.yaml" "$datafile"
+done
+for datafile in "$MESON_SOURCE_ROOT"/test/config/*; do
+    check_schema "$MESON_SOURCE_ROOT/schema/config/meta/schema.yaml" "$datafile"
 done
